//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTalentManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuOptionNode
    {
        public int MenuNodesId { get; set; }
        public int MenuId { get; set; }
        public string NodeDescription { get; set; }
        public string NodeControlName { get; set; }
        public int NodeHierarchy { get; set; }
        public string SubMenuName { get; set; }
        public bool AccessibleViaApp { get; set; }
    
        public virtual MenuOption MenuOption { get; set; }
    }
}
