//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTalentManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemUserGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SystemUserGroup()
        {
            this.SystemUserGroupAccesses = new HashSet<SystemUserGroupAccess>();
        }
    
        public int SystemUserGroupId { get; set; }
        public string GroupName { get; set; }
        public string AccessHierachyId { get; set; }
        public string Description { get; set; }
        public bool ApproveSessionTransactions { get; set; }
        public bool ModifyEmployeeContract { get; set; }
        public bool DeleteUnapproveTransactions { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string LastModidifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
    
        public virtual AccessHierachy AccessHierachy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SystemUserGroupAccess> SystemUserGroupAccesses { get; set; }
    }
}
