//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTalentManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SystemUser()
        {
            this.SystemUserPasswordHistories = new HashSet<SystemUserPasswordHistory>();
        }
    
        public int SystemUserId { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public byte[] UserImage { get; set; }
        public bool AccountExpirable { get; set; }
        public Nullable<int> ActivePeriod { get; set; }
        public bool RequireUserChange { get; set; }
        public Nullable<System.DateTime> ExpirableValidationDate { get; set; }
        public Nullable<bool> CurrentlyLoggedIn { get; set; }
        public Nullable<System.DateTime> LastPasswordChange { get; set; }
        public int SystemUserGroupId { get; set; }
        public bool AccountLocked { get; set; }
        public short DepartmentId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SystemUserPasswordHistory> SystemUserPasswordHistories { get; set; }
    }
}
