//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTalentManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemSecurityConfiguration
    {
        public int SystemSecurityConfigurationId { get; set; }
        public bool EnableAutoLogOut { get; set; }
        public int AutoLogOutMinutes { get; set; }
        public bool AutoLockUserAccount { get; set; }
        public int NoOfUnsuccessfulAttempts { get; set; }
        public bool ImposePasswordChange { get; set; }
        public int PasswordValidityDays { get; set; }
        public bool AllowPasswordRepeat { get; set; }
        public string LastModifiedBy { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
    }
}
