//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTalentManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemUserGroupAccess
    {
        public int UserGroupAccessId { get; set; }
        public int SystemUserGroupId { get; set; }
        public int MenuId { get; set; }
        public int MenuNodesId { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public string LastModifiedBy { get; set; }
    
        public virtual SystemUserGroup SystemUserGroup { get; set; }
    }
}
