//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTalentManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysUserAuditView
    {
        public int SystemUserId { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string UserName { get; set; }
        public System.DateTime LogInTime { get; set; }
        public Nullable<System.DateTime> LogOutTime { get; set; }
        public Nullable<int> TotalMinutesSpent { get; set; }
        public Nullable<int> Days { get; set; }
        public Nullable<int> Hours { get; set; }
        public Nullable<int> Minutes { get; set; }
        public string TotalTimeSpent { get; set; }
        public Nullable<System.DateTime> ConvertedTimeIn { get; set; }
    }
}
