//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTalentManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class TalentManager_ProductionView
    {
        public int ProductionLineId { get; set; }
        public short CompanyId { get; set; }
        public short DepartmentId { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public string CostCentre { get; set; }
        public decimal SessionDurationInHours { get; set; }
        public bool OvertimeApplies { get; set; }
        public decimal OvertimeCalculationStartHour { get; set; }
        public bool Active { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public string Department { get; set; }
        public string DepartmentDescription { get; set; }
        public string CompanyName { get; set; }
        public string CompanyDescription { get; set; }
    }
}
