//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTalentManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class TalentManager_EmployeeJobView
    {
        public int EmployeeJobId { get; set; }
        public int EmployeeId { get; set; }
        public System.DateTime JobDate { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public int DutyId { get; set; }
        public string DutyDescription { get; set; }
        public short DepartmentId { get; set; }
        public string DepartmentName { get; set; }
        public string ProductionLineDescription { get; set; }
        public decimal SessionDurationInHours { get; set; }
        public decimal WageRate { get; set; }
        public string WageTypeDescription { get; set; }
        public Nullable<decimal> UserDecidedPaymentAmount { get; set; }
        public string PaymentAmountDecidedByUser { get; set; }
        public int EmployeeContractId { get; set; }
        public bool IsApproved { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> DateApproved { get; set; }
        public bool IsExported { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string EmployeeRef { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public string Gender { get; set; }
        public string EmployeeDescription { get; set; }
        public int ProductionLineId { get; set; }
        public string Notes { get; set; }
        public short CompanyId { get; set; }
        public string CompanyName { get; set; }
        public decimal DailyWageRate { get; set; }
        public string PaymentType { get; set; }
        public decimal ActualHoursWorked { get; set; }
        public string CostCentre { get; set; }
        public decimal TaskPaymentAmount { get; set; }
        public decimal OvertimePaymentAmount { get; set; }
        public string EmployeeFullName { get; set; }
        public int TaskId { get; set; }
        public int EmployeeJobDetailId { get; set; }
        public bool IsVoided { get; set; }
        public string VoidReason { get; set; }
        public Nullable<System.DateTime> DateVoided { get; set; }
        public string VoidedBy { get; set; }
    }
}
