//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTalentManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class TalentManager_ContractedEmployeeView
    {
        public int EmployeeContractId { get; set; }
        public int EmployeeId { get; set; }
        public int TaskId { get; set; }
        public string ContractCode { get; set; }
        public System.DateTime ContractStartDate { get; set; }
        public System.DateTime ContractEndDate { get; set; }
        public decimal RateOfPay { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public string Gender { get; set; }
        public string EmployeeRef { get; set; }
        public string EmployeeDescription { get; set; }
        public string WageTypeDescription { get; set; }
        public decimal SessionDurationInHours { get; set; }
        public int ProductionLineId { get; set; }
        public string ProductionLineDescription { get; set; }
        public int DutyId { get; set; }
        public string DutyDescription { get; set; }
        public short DepartmentId { get; set; }
        public bool OvertimeApplicableToDuty { get; set; }
        public decimal OvertimeCalculationStartHour { get; set; }
        public bool IsActiveContract { get; set; }
        public short CompanyId { get; set; }
        public string CompanyDescription { get; set; }
        public bool OvertimeAppliesToProduction { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public byte[] Photo { get; set; }
        public string DepartmentName { get; set; }
        public decimal DayRate { get; set; }
        public string CostCentre { get; set; }
    }
}
