//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTalentManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class TalentManager_EmployeeJob
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TalentManager_EmployeeJob()
        {
            this.TalentManager_EmployeeJobDetail = new HashSet<TalentManager_EmployeeJobDetail>();
        }
    
        public int EmployeeJobId { get; set; }
        public int EmployeeId { get; set; }
        public System.DateTime JobDate { get; set; }
        public short CompanyId { get; set; }
        public string CompanyName { get; set; }
        public short DepartmentId { get; set; }
        public string DepartmentName { get; set; }
        public decimal DailyWageRate { get; set; }
        public string PaymentType { get; set; }
        public string Notes { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TalentManager_EmployeeJobDetail> TalentManager_EmployeeJobDetail { get; set; }
    }
}
