//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTalentManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class TalentManager_ExportedEmployeeJob
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TalentManager_ExportedEmployeeJob()
        {
            this.TalentManager_ExportedEmployeeJobDetails = new HashSet<TalentManager_ExportedEmployeeJobDetails>();
        }
    
        public int ExportedEmployeeJobId { get; set; }
        public short CompanyId { get; set; }
        public int PayrollPeriod { get; set; }
        public int PayrollYear { get; set; }
        public int EmployeeCount { get; set; }
        public decimal PayrollAmount { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TalentManager_ExportedEmployeeJobDetails> TalentManager_ExportedEmployeeJobDetails { get; set; }
    }
}
