//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTalentManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class TalentManager_SystemNumberConfig
    {
        public int SystemNumberConfigId { get; set; }
        public string ObjectType { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string ObjectMask { get; set; }
        public int NextSystemNumber { get; set; }
        public bool UsePadding { get; set; }
        public int PaddingAmount { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
    }
}
