//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTalentManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class TalentManager_EmployeeView
    {
        public int EmployeeId { get; set; }
        public string EmployeeDescription { get; set; }
        public string CompanyDescription { get; set; }
        public string EmployeeRef { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public byte[] Photo { get; set; }
    }
}
