//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTalentManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class TalentManager_ExportedEmployeeJobDetails
    {
        public int ExportedEmployeeJobDetailId { get; set; }
        public int ExportedEmployeeJobId { get; set; }
        public int EmployeeJobDetailId { get; set; }
        public decimal AmountPaid { get; set; }
    
        public virtual TalentManager_ExportedEmployeeJob TalentManager_ExportedEmployeeJob { get; set; }
    }
}
