//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTalentManagement
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SMARTPayEntities : DbContext
    {
        public SMARTPayEntities()
            : base("name=SMARTPayEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TalentManager_WageType> TalentManager_WageType { get; set; }
        public virtual DbSet<TalentManager_DutyCodeView> TalentManager_DutyCodeView { get; set; }
        public virtual DbSet<TalentManager_DepartmentView> TalentManager_DepartmentView { get; set; }
        public virtual DbSet<TalentManager_SessionSpan> TalentManager_SessionSpan { get; set; }
        public virtual DbSet<TalentManager_ProductionLine> TalentManager_ProductionLine { get; set; }
        public virtual DbSet<AccessHierachy> AccessHierachies { get; set; }
        public virtual DbSet<MenuOptionNode> MenuOptionNodes { get; set; }
        public virtual DbSet<MenuOption> MenuOptions { get; set; }
        public virtual DbSet<SystemSecurityConfiguration> SystemSecurityConfigurations { get; set; }
        public virtual DbSet<SystemUserAccess> SystemUserAccesses { get; set; }
        public virtual DbSet<SystemUserGroup> SystemUserGroups { get; set; }
        public virtual DbSet<SystemUserGroupAccess> SystemUserGroupAccesses { get; set; }
        public virtual DbSet<SystemUserPasswordHistory> SystemUserPasswordHistories { get; set; }
        public virtual DbSet<SystemUser> SystemUsers { get; set; }
        public virtual DbSet<SystemUserSetting> SystemUserSettings { get; set; }
        public virtual DbSet<SystemMenuView> SystemMenuViews { get; set; }
        public virtual DbSet<SysUserAuditView> SysUserAuditViews { get; set; }
        public virtual DbSet<TalentManager_CompanyView> TalentManager_CompanyView { get; set; }
        public virtual DbSet<TalentManager_ProductionView> TalentManager_ProductionView { get; set; }
        public virtual DbSet<TalentManager_Task> TalentManager_Task { get; set; }
        public virtual DbSet<TalentManager_TaskView> TalentManager_TaskView { get; set; }
        public virtual DbSet<TalentManager_EmployeeView> TalentManager_EmployeeView { get; set; }
        public virtual DbSet<TalentManager_EmployeeContract> TalentManager_EmployeeContract { get; set; }
        public virtual DbSet<TalentManager_ContractedEmployeeView> TalentManager_ContractedEmployeeView { get; set; }
        public virtual DbSet<TalentManager_PaymentType> TalentManager_PaymentType { get; set; }
        public virtual DbSet<TalentManager_EmployeeJobView> TalentManager_EmployeeJobView { get; set; }
        public virtual DbSet<TalentManager_EmployeeDayRate> TalentManager_EmployeeDayRate { get; set; }
        public virtual DbSet<TalentManager_EmployeeJob> TalentManager_EmployeeJob { get; set; }
        public virtual DbSet<TalentManager_EmployeeJobDetail> TalentManager_EmployeeJobDetail { get; set; }
        public virtual DbSet<TalentManager_ExportedEmployeeJob> TalentManager_ExportedEmployeeJob { get; set; }
        public virtual DbSet<TalentManager_ExportedEmployeeJobDetails> TalentManager_ExportedEmployeeJobDetails { get; set; }
        public virtual DbSet<TalentManager_SystemNumberConfig> TalentManager_SystemNumberConfig { get; set; }
    }
}
